# LVR2 dependency acquisition helpers.
#
# vcpkg-first dependency policy makes vcpkg the primary dependency path while preserving explicit
# per-package system package escape hatches. Include this file before calling
# lvr2_find_package().

macro(lvr2_find_package _LVR2_FIND_PACKAGE_NAME)
  string(REGEX REPLACE "[^A-Za-z0-9]" "_" _LVR2_FIND_PACKAGE_OPTION "${_LVR2_FIND_PACKAGE_NAME}")
  string(TOUPPER "${_LVR2_FIND_PACKAGE_OPTION}" _LVR2_FIND_PACKAGE_OPTION)

  if(LVR2_WITH_VCPKG AND DEFINED LVR2_USE_SYSTEM_${_LVR2_FIND_PACKAGE_OPTION} AND LVR2_USE_SYSTEM_${_LVR2_FIND_PACKAGE_OPTION})
    message(STATUS "LVR2_USE_SYSTEM_${_LVR2_FIND_PACKAGE_OPTION}=ON: preferring system/env lookup for ${_LVR2_FIND_PACKAGE_NAME}")

    set(_LVR2_SAVED_FIND_USE_CMAKE_SYSTEM_PATH ${CMAKE_FIND_USE_CMAKE_SYSTEM_PATH})
    set(_LVR2_SAVED_FIND_USE_SYSTEM_ENVIRONMENT_PATH ${CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH})
    set(_LVR2_SAVED_IGNORE_PREFIX_PATH "${CMAKE_IGNORE_PREFIX_PATH}")

    set(_LVR2_VCPKG_IGNORED_PREFIXES "")
    if(DEFINED VCPKG_INSTALLED_DIR)
      list(APPEND _LVR2_VCPKG_IGNORED_PREFIXES "${VCPKG_INSTALLED_DIR}")
      if(DEFINED VCPKG_TARGET_TRIPLET)
        list(APPEND _LVR2_VCPKG_IGNORED_PREFIXES "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
      endif()
    endif()
    if(DEFINED ENV{VCPKG_ROOT})
      list(APPEND _LVR2_VCPKG_IGNORED_PREFIXES "$ENV{VCPKG_ROOT}/installed")
      if(DEFINED VCPKG_TARGET_TRIPLET)
        list(APPEND _LVR2_VCPKG_IGNORED_PREFIXES "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
      endif()
    endif()

    foreach(_LVR2_VCPKG_PREFIX IN LISTS _LVR2_VCPKG_IGNORED_PREFIXES)
      if(_LVR2_VCPKG_PREFIX)
        get_filename_component(_LVR2_VCPKG_PREFIX_ABS "${_LVR2_VCPKG_PREFIX}" ABSOLUTE)
        list(APPEND CMAKE_IGNORE_PREFIX_PATH "${_LVR2_VCPKG_PREFIX_ABS}")
      endif()
    endforeach()
    if(CMAKE_IGNORE_PREFIX_PATH)
      list(REMOVE_DUPLICATES CMAKE_IGNORE_PREFIX_PATH)
    endif()

    set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH ON)
    set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH ON)
    find_package(${ARGV})

    set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH ${_LVR2_SAVED_FIND_USE_CMAKE_SYSTEM_PATH})
    set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH ${_LVR2_SAVED_FIND_USE_SYSTEM_ENVIRONMENT_PATH})
    set(CMAKE_IGNORE_PREFIX_PATH "${_LVR2_SAVED_IGNORE_PREFIX_PATH}")
  else()
    find_package(${ARGV})
  endif()
endmacro()
