if(NOT DEFINED LVR2_SOURCE_DIR)
  get_filename_component(LVR2_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

if(CMAKE_VERSION VERSION_LESS 4.2)
  message(FATAL_ERROR "LVR3 Lyrical/Resolute verification requires CMake 4.2 or newer; provision the target toolchain before running presets or configure")
endif()

function(_lvr2_read _relative _out)
  set(_path "${LVR2_SOURCE_DIR}/${_relative}")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "Required toolchain-contract file is missing: ${_relative}")
  endif()
  file(READ "${_path}" _text)
  set(${_out} "${_text}" PARENT_SCOPE)
endfunction()

_lvr2_read("CMakeLists.txt" _root_cmake)
if(NOT _root_cmake MATCHES "cmake_minimum_required\\(VERSION 4\\.2")
  message(FATAL_ERROR "Top-level CMakeLists.txt must require CMake 4.2 for the Lyrical/Resolute toolchain")
endif()

_lvr2_read("CMakePresets.json" _presets)
foreach(_required_json IN ITEMS "\"cmakeMinimumRequired\"" "\"major\": 4" "\"minor\": 2")
  string(FIND "${_presets}" "${_required_json}" _json_pos)
  if(_json_pos EQUAL -1)
    message(FATAL_ERROR "CMakePresets.json must declare cmakeMinimumRequired 4.2: ${_required_json}")
  endif()
endforeach()

_lvr2_read("README.md" _readme)
foreach(_required_readme IN ITEMS "CMake 4.2 or newer" "docs/cmake/toolchain-contract.md")
  string(FIND "${_readme}" "${_required_readme}" _readme_pos)
  if(_readme_pos EQUAL -1)
    message(FATAL_ERROR "README.md must document the CMake toolchain contract: ${_required_readme}")
  endif()
endforeach()

_lvr2_read("docs/cmake/toolchain-contract.md" _contract_doc)
foreach(_required_doc IN ITEMS "CMake 4.2 or newer" "cmake_minimum_required(VERSION 4.2)" "cmakeMinimumRequired" "cmake --list-presets=all")
  string(FIND "${_contract_doc}" "${_required_doc}" _doc_pos)
  if(_doc_pos EQUAL -1)
    message(FATAL_ERROR "docs/cmake/toolchain-contract.md is missing required contract text: ${_required_doc}")
  endif()
endforeach()

_lvr2_read("tests/CMakeLists.txt" _tests_cmake)
if(NOT _tests_cmake MATCHES "lvr2_cmake_toolchain_contract")
  message(FATAL_ERROR "tests/CMakeLists.txt must register lvr2_cmake_toolchain_contract")
endif()

_lvr2_read(".github/workflows/ci-smoke.yml" _github_ci)
foreach(_required_github IN ITEMS "cmake --version" "cmake --list-presets=all" "cmake_toolchain_contract")
  string(FIND "${_github_ci}" "${_required_github}" _github_pos)
  if(_github_pos EQUAL -1)
    message(FATAL_ERROR "GitHub CI must record and enforce the CMake toolchain contract: ${_required_github}")
  endif()
endforeach()

_lvr2_read(".gitlab-ci.yml" _gitlab_ci)
foreach(_required_gitlab IN ITEMS "cmake --version" "cmake --list-presets=all" "cmake_toolchain_contract")
  string(FIND "${_gitlab_ci}" "${_required_gitlab}" _gitlab_pos)
  if(_gitlab_pos EQUAL -1)
    message(FATAL_ERROR "GitLab CI must record and enforce the CMake toolchain contract: ${_required_gitlab}")
  endif()
endforeach()

message(STATUS "CMake toolchain contract guard passed")
