if(NOT DEFINED LVR2_SOURCE_DIR)
  message(FATAL_ERROR "LVR2_SOURCE_DIR is required")
endif()

set(_packaging_required_files
  package.xml
  debian/control
  debian/rules
  debian/liblvr2-dev.install
  debian/liblvr2-cuda-dev.install
  cmake/Lvr3Packaging.cmake
  cmake/Lvr3Install.cmake
  cmake/lvr2-config.cmake.in
  cmake/lvr3-config.cmake.in
  cmake/lvr-dependencies.cmake.in
)
foreach(_packaging_file IN LISTS _packaging_required_files)
  if(NOT EXISTS "${LVR2_SOURCE_DIR}/${_packaging_file}")
    message(FATAL_ERROR "Required packaging file is missing: ${_packaging_file}")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/CMakeLists.txt" _root_cmake)
if(NOT _root_cmake MATCHES "project\\(lvr3 VERSION")
  message(FATAL_ERROR "Top-level CMake project identity must be lvr3")
endif()

file(READ "${LVR2_SOURCE_DIR}/package.xml" _package_xml)
if(NOT _package_xml MATCHES "<name>lvr3</name>")
  message(FATAL_ERROR "ROS package identity must be lvr3")
endif()
foreach(_baseline_token IN ITEMS "ROS 2 Lyrical" "Ubuntu Resolute 26.04" "C++20")
  string(FIND "${_package_xml}" "${_baseline_token}" _baseline_token_pos)
  if(_baseline_token_pos EQUAL -1)
    message(FATAL_ERROR "package.xml must document the active Lyrical/Resolute/C++20 packaging lane: ${_baseline_token}")
  endif()
endforeach()
foreach(_rosdep_key IN ITEMS libexpected-dev spdlog assimp)
  if(NOT _package_xml MATCHES "<depend>${_rosdep_key}</depend>")
    message(FATAL_ERROR "package.xml must declare verified rosdep dependency '${_rosdep_key}'")
  endif()
endforeach()
if(_package_xml MATCHES "<depend>libfmt-dev</depend>")
  message(FATAL_ERROR "package.xml must not retain the removed fmt dependency")
endif()

file(READ "${LVR2_SOURCE_DIR}/cmake/Lvr3Install.cmake" _install_cmake)
if(NOT _install_cmake MATCHES "DESTINATION share/lvr3")
  message(FATAL_ERROR "package.xml must install under share/lvr3")
endif()
if(_install_cmake MATCHES "DESTINATION share/lvr2")
  message(FATAL_ERROR "package.xml must not install under legacy share/lvr2")
endif()
string(FIND "${_install_cmake}" [=[DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lvr3]=] _lvr3_install_dir_pos)
if(_lvr3_install_dir_pos EQUAL -1)
  message(FATAL_ERROR "lvr3 CMake package files must install under lib/cmake/lvr3")
endif()
string(FIND "${_install_cmake}" [=[DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lvr3)]=] _lvr3_target_export_pos)
if(_lvr3_target_export_pos EQUAL -1)
  message(FATAL_ERROR "lvr3 CMake package must install a local compatibility target export")
endif()

file(READ "${LVR2_SOURCE_DIR}/cmake/lvr3-config.cmake.in" _lvr3_config_template)
string(FIND "${_lvr3_config_template}" [=[include(${CMAKE_CURRENT_LIST_DIR}/lvr-dependencies.cmake)]=] _lvr3_dependency_include_pos)
if(_lvr3_dependency_include_pos EQUAL -1)
  message(FATAL_ERROR "lvr3 config must load its own dependency helper")
endif()
string(FIND "${_lvr3_config_template}" [=[include(${CMAKE_CURRENT_LIST_DIR}/lvr2-targets.cmake)]=] _lvr3_targets_include_pos)
if(_lvr3_targets_include_pos EQUAL -1)
  message(FATAL_ERROR "lvr3 config must import its local target export")
endif()
if(_lvr3_config_template MATCHES "find_dependency\\(lvr2|lvr2-config.cmake")
  message(FATAL_ERROR "lvr3 config must not delegate to the legacy lvr2 package")
endif()

file(READ "${LVR2_SOURCE_DIR}/cmake/Lvr3Packaging.cmake" _cpack_identity)
if(NOT _cpack_identity MATCHES "CPACK_PACKAGE_NAME \\\"lvr3\\\"")
  message(FATAL_ERROR "CPack package identity must be lvr3")
endif()
string(FIND "${_cpack_identity}" [=[lvr3-${PROJECT_VERSION}]=] _cpack_lvr3_name_pos)
if(_cpack_lvr3_name_pos EQUAL -1)
  message(FATAL_ERROR "CPack archive names must use lvr3")
endif()

file(READ "${LVR2_SOURCE_DIR}/migration_guide.md" _migration_guide)
foreach(_identity_note IN ITEMS "share/lvr3" "find_package(lvr2)" "Debian source and binary package names")
  string(FIND "${_migration_guide}" "${_identity_note}" _identity_note_pos)
  if(_identity_note_pos EQUAL -1)
    message(FATAL_ERROR "Migration guide must document package identity/compatibility note: ${_identity_note}")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/debian/control" _debian_control)
if(NOT _debian_control MATCHES "(^|\n)Source: lvr2(\n|$)")
  message(FATAL_ERROR "Debian source package identity remains lvr2 as an explicit compatibility package")
endif()
foreach(_binary_pkg IN ITEMS liblvr2-dev liblvr2 lvr2-bin liblvr2-cuda-dev liblvr2-cuda lvr2-cuda-bin)
  if(NOT _debian_control MATCHES "(^|\n)Package: ${_binary_pkg}(\n|$)")
    message(FATAL_ERROR "Expected Debian binary package '${_binary_pkg}' is missing")
  endif()
endforeach()
foreach(_debian_dep IN ITEMS libassimp-dev libexpected-dev libspdlog-dev libtbb-dev libtiff-dev libgdal-dev libhdf5-dev pkg-config)
  if(NOT _debian_control MATCHES "(^|[, \n])${_debian_dep}([, \n(]|$)")
    message(FATAL_ERROR "debian/control must include verified package-backed dependency '${_debian_dep}'")
  endif()
endforeach()
if(_debian_control MATCHES "(^|[, \n])libfmt-dev([, \n(]|$)")
  message(FATAL_ERROR "debian/control must not retain the removed libfmt-dev dependency")
endif()
foreach(_viewer_dep IN ITEMS libvtk6-qt-dev libvtk9-qt-dev qtbase5-dev)
  if(_debian_control MATCHES "(^|[, \n])${_viewer_dep}([, \n(]|$)")
    message(FATAL_ERROR "debian/control must not depend on removed bundled-viewer dependency '${_viewer_dep}'")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/cmake/Lvr3Packaging.cmake" _cpack_packaging)
foreach(_debian_dep IN ITEMS libassimp-dev libexpected-dev libspdlog-dev libtbb-dev libtiff-dev libgdal-dev libhdf5-dev pkg-config)
  if(NOT _cpack_packaging MATCHES "(^|[; \n])${_debian_dep}([; \n)]|$)")
    message(FATAL_ERROR "CPack Debian metadata must include verified package-backed dependency '${_debian_dep}'")
  endif()
endforeach()
if(_cpack_packaging MATCHES "(^|[; \n])libfmt-dev([; \n)]|$)")
  message(FATAL_ERROR "CPack Debian metadata must not retain the removed libfmt-dev dependency")
endif()
foreach(_unverified_dep IN ITEMS libhighfive-dev highfive librply-dev rply liblaslib-dev laslib lastools)
  if(_debian_control MATCHES "(^|[, \n])${_unverified_dep}([, \n(]|$)")
    message(FATAL_ERROR "debian/control must not invent unverified dependency '${_unverified_dep}'")
  endif()
  if(_cpack_packaging MATCHES "(^|[; \n])${_unverified_dep}([; \n)]|$)")
    message(FATAL_ERROR "CPack Debian metadata must not invent unverified dependency '${_unverified_dep}'")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/debian/rules" _debian_rules)
foreach(_required_flag IN ITEMS "-DLVR2_WITH_VCPKG=OFF" "-DBUILD_SHARED_LIBS=ON" "-DLVR2_BUILD_STATIC_LIBS=OFF")
  string(REGEX MATCHALL "${_required_flag}" _flag_matches "${_debian_rules}")
  list(LENGTH _flag_matches _flag_count)
  if(_flag_count LESS 2)
    message(FATAL_ERROR "debian/rules must pass ${_required_flag} to both configure paths")
  endif()
endforeach()
if(NOT _debian_rules MATCHES "-DLVR2_WITH_CUDA=OFF")
  message(FATAL_ERROR "CPU Debian configure path must keep CUDA disabled")
endif()
if(_debian_rules MATCHES "LVR2_USE_SYSTEM_ASSIMP")
  message(FATAL_ERROR "Assimp must remain private; do not add a public LVR2_USE_SYSTEM_ASSIMP option")
endif()

foreach(_install_file IN ITEMS debian/liblvr2-dev.install debian/liblvr2-cuda-dev.install)
  file(READ "${LVR2_SOURCE_DIR}/${_install_file}" _install_text)
  if(_install_text MATCHES "lib\\*\\.a|/lib\\*.a|HighFive")
    message(FATAL_ERROR "${_install_file} must not install static archives or vendored HighFive artifacts")
  endif()
endforeach()

message(STATUS "ROS/Debian packaging policy guard passed")
