if(NOT DEFINED LVR2_SOURCE_DIR)
  message(FATAL_ERROR "LVR2_SOURCE_DIR is required")
endif()

set(_packaging_required_files
  package.xml
  debian/control
  debian/rules
  debian/liblvr2-dev.install
  debian/liblvr2-cuda-dev.install
  cmake/Lvr3Packaging.cmake
)
foreach(_packaging_file IN LISTS _packaging_required_files)
  if(NOT EXISTS "${LVR2_SOURCE_DIR}/${_packaging_file}")
    message(FATAL_ERROR "Required packaging file is missing: ${_packaging_file}")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/package.xml" _package_xml)
if(NOT _package_xml MATCHES "<name>lvr2</name>")
  message(FATAL_ERROR "ROS package identity must remain lvr2 until an ADR-backed rename slice")
endif()
foreach(_rosdep_key IN ITEMS libexpected-dev spdlog assimp)
  if(NOT _package_xml MATCHES "<depend>${_rosdep_key}</depend>")
    message(FATAL_ERROR "package.xml must declare verified rosdep dependency '${_rosdep_key}'")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/debian/control" _debian_control)
if(NOT _debian_control MATCHES "(^|\n)Source: lvr2(\n|$)")
  message(FATAL_ERROR "Debian source package identity must remain lvr2")
endif()
foreach(_binary_pkg IN ITEMS liblvr2-dev liblvr2 lvr2-bin liblvr2-cuda-dev liblvr2-cuda lvr2-cuda-bin)
  if(NOT _debian_control MATCHES "(^|\n)Package: ${_binary_pkg}(\n|$)")
    message(FATAL_ERROR "Expected Debian binary package '${_binary_pkg}' is missing")
  endif()
endforeach()
foreach(_debian_dep IN ITEMS libassimp-dev libexpected-dev libspdlog-dev libtbb-dev libtiff-dev libgdal-dev libhdf5-dev pkg-config)
  if(NOT _debian_control MATCHES "(^|[, \n])${_debian_dep}([, \n(]|$)")
    message(FATAL_ERROR "debian/control must include verified package-backed dependency '${_debian_dep}'")
  endif()
endforeach()
foreach(_viewer_dep IN ITEMS libvtk6-qt-dev libvtk9-qt-dev qtbase5-dev)
  if(_debian_control MATCHES "(^|[, \n])${_viewer_dep}([, \n(]|$)")
    message(FATAL_ERROR "debian/control must not depend on removed bundled-viewer dependency '${_viewer_dep}'")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/cmake/Lvr3Packaging.cmake" _cpack_packaging)
foreach(_debian_dep IN ITEMS libassimp-dev libexpected-dev libspdlog-dev libtbb-dev libtiff-dev libgdal-dev libhdf5-dev pkg-config)
  if(NOT _cpack_packaging MATCHES "(^|[; \n])${_debian_dep}([; \n)]|$)")
    message(FATAL_ERROR "CPack Debian metadata must include verified package-backed dependency '${_debian_dep}'")
  endif()
endforeach()
foreach(_unverified_dep IN ITEMS libhighfive-dev highfive librply-dev rply liblaslib-dev laslib lastools)
  if(_debian_control MATCHES "(^|[, \n])${_unverified_dep}([, \n(]|$)")
    message(FATAL_ERROR "debian/control must not invent unverified dependency '${_unverified_dep}'")
  endif()
  if(_cpack_packaging MATCHES "(^|[; \n])${_unverified_dep}([; \n)]|$)")
    message(FATAL_ERROR "CPack Debian metadata must not invent unverified dependency '${_unverified_dep}'")
  endif()
endforeach()

file(READ "${LVR2_SOURCE_DIR}/debian/rules" _debian_rules)
foreach(_required_flag IN ITEMS "-DLVR2_WITH_VCPKG=OFF" "-DBUILD_SHARED_LIBS=ON" "-DLVR2_BUILD_STATIC_LIBS=OFF")
  string(REGEX MATCHALL "${_required_flag}" _flag_matches "${_debian_rules}")
  list(LENGTH _flag_matches _flag_count)
  if(_flag_count LESS 2)
    message(FATAL_ERROR "debian/rules must pass ${_required_flag} to both configure paths")
  endif()
endforeach()
if(NOT _debian_rules MATCHES "-DLVR2_WITH_CUDA=OFF")
  message(FATAL_ERROR "CPU Debian configure path must keep CUDA disabled")
endif()
if(_debian_rules MATCHES "LVR2_USE_SYSTEM_ASSIMP")
  message(FATAL_ERROR "Assimp must remain private; do not add a public LVR2_USE_SYSTEM_ASSIMP option")
endif()

foreach(_install_file IN ITEMS debian/liblvr2-dev.install debian/liblvr2-cuda-dev.install)
  file(READ "${LVR2_SOURCE_DIR}/${_install_file}" _install_text)
  if(_install_text MATCHES "lib\\*\\.a|/lib\\*.a|HighFive")
    message(FATAL_ERROR "${_install_file} must not install static archives or vendored HighFive artifacts")
  endif()
endforeach()

message(STATUS "ROS/Debian packaging policy guard passed")
