# Verifies a single package identity load order from an installed prefix.

cmake_minimum_required(VERSION 4.2)
project(PackageIdentityLoadOrder C CXX)

if(NOT DEFINED CHECK_PREFIX OR CHECK_PREFIX STREQUAL "")
  message(FATAL_ERROR "CHECK_PREFIX must be provided")
endif()
if(NOT DEFINED CHECK_ORDER OR CHECK_ORDER STREQUAL "")
  message(FATAL_ERROR "CHECK_ORDER must be provided")
endif()
if(NOT DEFINED CHECK_SHAPE OR CHECK_SHAPE STREQUAL "")
  set(CHECK_SHAPE "requested")
endif()

list(PREPEND CMAKE_PREFIX_PATH "${CHECK_PREFIX}")
set(lvr2_DIR "${CHECK_PREFIX}/lib/cmake/lvr2")
set(lvr3_DIR "${CHECK_PREFIX}/lib/cmake/lvr3")
set(_LVR_COMPONENTS geometry io reconstruction texture registration display)
set(_LVR_UNKNOWN_COMPONENT definitely_missing)

if(CHECK_ORDER STREQUAL "legacy")
  find_package(lvr2 CONFIG REQUIRED COMPONENTS ${_LVR_COMPONENTS})

  if(NOT TARGET lvr2::lvr2)
    message(FATAL_ERROR "find_package(lvr2) did not provide lvr2::lvr2")
  endif()
  if(NOT DEFINED LVR2_INCLUDE_DIRS OR NOT DEFINED LVR2_DEFINITIONS)
    message(FATAL_ERROR "lvr2 package variables are incomplete")
  endif()

elseif(CHECK_ORDER STREQUAL "modern")
  find_package(lvr3 CONFIG REQUIRED COMPONENTS ${_LVR_COMPONENTS})

  if(NOT TARGET lvr3::lvr3)
    message(FATAL_ERROR "find_package(lvr3) did not provide lvr3::lvr3")
  endif()
  if(NOT DEFINED LVR3_INCLUDE_DIRS OR NOT DEFINED LVR3_DEFINITIONS OR NOT DEFINED LVR3_LIBRARIES)
    message(FATAL_ERROR "lvr3 package variables are incomplete")
  endif()

elseif(CHECK_ORDER STREQUAL "legacy_then_modern")
  find_package(lvr2 CONFIG REQUIRED COMPONENTS ${_LVR_COMPONENTS})
  find_package(lvr3 CONFIG REQUIRED COMPONENTS ${_LVR_COMPONENTS})

  if(NOT TARGET lvr2::lvr2)
    message(FATAL_ERROR "find_package(lvr2) did not provide lvr2::lvr2")
  endif()
  if(NOT TARGET lvr3::lvr3)
    message(FATAL_ERROR "find_package(lvr3) did not provide lvr3::lvr3")
  endif()

elseif(CHECK_ORDER STREQUAL "modern_then_legacy")
  find_package(lvr3 CONFIG REQUIRED COMPONENTS ${_LVR_COMPONENTS})
  find_package(lvr2 CONFIG REQUIRED COMPONENTS ${_LVR_COMPONENTS})

  if(NOT TARGET lvr3::lvr3)
    message(FATAL_ERROR "find_package(lvr3) did not provide lvr3::lvr3")
  endif()
  if(NOT TARGET lvr2::lvr2)
    message(FATAL_ERROR "find_package(lvr2) did not provide lvr2::lvr2 after loading lvr3")
  endif()

elseif(CHECK_ORDER STREQUAL "legacy_unknown_quiet")
  find_package(lvr2 CONFIG QUIET COMPONENTS ${_LVR_UNKNOWN_COMPONENT})
  if(lvr2_FOUND OR LVR2_FOUND)
    message(FATAL_ERROR "find_package(lvr2 QUIET COMPONENTS ${_LVR_UNKNOWN_COMPONENT}) should report not found")
  endif()
  if(NOT DEFINED lvr2_${_LVR_UNKNOWN_COMPONENT}_FOUND OR lvr2_${_LVR_UNKNOWN_COMPONENT}_FOUND)
    message(FATAL_ERROR "lvr2 quiet unknown component did not set a false component found variable")
  endif()
  message(STATUS "Package identity smoke check '${CHECK_SHAPE}/${CHECK_ORDER}' passed")
  return()

elseif(CHECK_ORDER STREQUAL "modern_unknown_quiet")
  find_package(lvr3 CONFIG QUIET COMPONENTS ${_LVR_UNKNOWN_COMPONENT})
  if(lvr3_FOUND OR LVR3_FOUND)
    message(FATAL_ERROR "find_package(lvr3 QUIET COMPONENTS ${_LVR_UNKNOWN_COMPONENT}) should report not found")
  endif()
  if(NOT DEFINED lvr3_${_LVR_UNKNOWN_COMPONENT}_FOUND OR lvr3_${_LVR_UNKNOWN_COMPONENT}_FOUND)
    message(FATAL_ERROR "lvr3 quiet unknown component did not set a false component found variable")
  endif()
  message(STATUS "Package identity smoke check '${CHECK_SHAPE}/${CHECK_ORDER}' passed")
  return()

elseif(CHECK_ORDER STREQUAL "legacy_unknown_optional")
  find_package(lvr2 CONFIG REQUIRED OPTIONAL_COMPONENTS ${_LVR_UNKNOWN_COMPONENT})
  if(NOT lvr2_FOUND OR NOT LVR2_FOUND)
    message(FATAL_ERROR "find_package(lvr2 OPTIONAL_COMPONENTS ${_LVR_UNKNOWN_COMPONENT}) should keep the package found")
  endif()
  if(NOT DEFINED lvr2_${_LVR_UNKNOWN_COMPONENT}_FOUND OR lvr2_${_LVR_UNKNOWN_COMPONENT}_FOUND)
    message(FATAL_ERROR "lvr2 optional unknown component did not set a false component found variable")
  endif()
  message(STATUS "Package identity smoke check '${CHECK_SHAPE}/${CHECK_ORDER}' passed")
  return()

elseif(CHECK_ORDER STREQUAL "modern_unknown_optional")
  find_package(lvr3 CONFIG REQUIRED OPTIONAL_COMPONENTS ${_LVR_UNKNOWN_COMPONENT})
  if(NOT lvr3_FOUND OR NOT LVR3_FOUND)
    message(FATAL_ERROR "find_package(lvr3 OPTIONAL_COMPONENTS ${_LVR_UNKNOWN_COMPONENT}) should keep the package found")
  endif()
  if(NOT DEFINED lvr3_${_LVR_UNKNOWN_COMPONENT}_FOUND OR lvr3_${_LVR_UNKNOWN_COMPONENT}_FOUND)
    message(FATAL_ERROR "lvr3 optional unknown component did not set a false component found variable")
  endif()
  message(STATUS "Package identity smoke check '${CHECK_SHAPE}/${CHECK_ORDER}' passed")
  return()

elseif(CHECK_ORDER STREQUAL "legacy_unknown_required")
  find_package(lvr2 CONFIG REQUIRED COMPONENTS ${_LVR_UNKNOWN_COMPONENT})
  message(FATAL_ERROR "find_package(lvr2 REQUIRED COMPONENTS ${_LVR_UNKNOWN_COMPONENT}) unexpectedly succeeded")

elseif(CHECK_ORDER STREQUAL "modern_unknown_required")
  find_package(lvr3 CONFIG REQUIRED COMPONENTS ${_LVR_UNKNOWN_COMPONENT})
  message(FATAL_ERROR "find_package(lvr3 REQUIRED COMPONENTS ${_LVR_UNKNOWN_COMPONENT}) unexpectedly succeeded")

else()
  message(FATAL_ERROR "Unknown CHECK_ORDER '${CHECK_ORDER}'")
endif()

# Verify canonical package target and conditional static target mapping.
if(TARGET lvr3::lvr3)
  get_target_property(_LVR3_ALIAS_TARGET lvr3::lvr3 ALIASED_TARGET)
  if(_LVR3_ALIAS_TARGET AND TARGET lvr2::lvr2 AND NOT _LVR3_ALIAS_TARGET STREQUAL "lvr2::lvr2")
    message(FATAL_ERROR "lvr3::lvr3 should alias the lvr2 aggregate target, got '${_LVR3_ALIAS_TARGET}'")
  endif()
endif()
if(TARGET lvr2::lvr2_static AND NOT TARGET lvr3::lvr3_static AND TARGET lvr3::lvr3)
  message(FATAL_ERROR "lvr2 static target exists but lvr3::lvr3_static alias is missing")
endif()
if(CHECK_SHAPE STREQUAL "shared-only" AND TARGET lvr3::lvr3_static)
  message(FATAL_ERROR "shared-only shape should not provide lvr3::lvr3_static")
endif()
if((CHECK_SHAPE STREQUAL "static-only" OR CHECK_SHAPE STREQUAL "dual") AND TARGET lvr3::lvr3)
  if(NOT TARGET lvr3::lvr3_static)
    message(FATAL_ERROR "${CHECK_SHAPE} shape should provide lvr3::lvr3_static")
  endif()
  if(DEFINED LVR3_LIBRARIES AND NOT "${LVR3_LIBRARIES}" STREQUAL "lvr3::lvr3_static")
    message(FATAL_ERROR "${CHECK_SHAPE} shape should prefer lvr3::lvr3_static in LVR3_LIBRARIES, got '${LVR3_LIBRARIES}'")
  endif()
endif()

foreach(_COMPONENT IN LISTS _LVR_COMPONENTS)
  if(NOT TARGET lvr2::${_COMPONENT})
    message(FATAL_ERROR "find_package(lvr2/lvr3) did not provide lvr2::${_COMPONENT}")
  endif()
  if(NOT lvr2_${_COMPONENT}_FOUND OR NOT LVR2_${_COMPONENT}_FOUND)
    message(FATAL_ERROR "lvr2 component '${_COMPONENT}' did not set component found variables")
  endif()

  if(TARGET lvr3::lvr3)
    if(NOT TARGET lvr3::${_COMPONENT})
      message(FATAL_ERROR "find_package(lvr3) did not provide lvr3::${_COMPONENT}")
    endif()
    get_target_property(_LVR3_COMPONENT_ALIAS lvr3::${_COMPONENT} ALIASED_TARGET)
    if(_LVR3_COMPONENT_ALIAS AND NOT _LVR3_COMPONENT_ALIAS STREQUAL "lvr2::${_COMPONENT}")
      message(FATAL_ERROR "lvr3::${_COMPONENT} should alias lvr2::${_COMPONENT}, got '${_LVR3_COMPONENT_ALIAS}'")
    endif()
    if(NOT lvr3_${_COMPONENT}_FOUND OR NOT LVR3_${_COMPONENT}_FOUND)
      message(FATAL_ERROR "lvr3 component '${_COMPONENT}' did not set component found variables")
    endif()
  endif()
endforeach()

string(CONCAT _PRIVATE_BACKEND_LOWER "as" "simp")
string(CONCAT _PRIVATE_BACKEND_UPPER "AS" "SIMP")
string(CONCAT _PRIVATE_BACKEND_CAMEL "As" "simp")
set(_PUBLIC_TARGETS lvr2::lvr2 lvr2::lvr2_static lvr3::lvr3 lvr3::lvr3_static)
foreach(_COMPONENT IN LISTS _LVR_COMPONENTS)
  list(APPEND _PUBLIC_TARGETS lvr2::${_COMPONENT} lvr3::${_COMPONENT})
endforeach()
set(_PUBLIC_PROPERTIES INTERFACE_LINK_LIBRARIES INTERFACE_INCLUDE_DIRECTORIES INTERFACE_COMPILE_DEFINITIONS)
foreach(_TARGET IN LISTS _PUBLIC_TARGETS)
  if(TARGET ${_TARGET})
    get_target_property(_COMPILE_FEATURES ${_TARGET} INTERFACE_COMPILE_FEATURES)
    if(NOT _COMPILE_FEATURES OR NOT ";${_COMPILE_FEATURES};" MATCHES ";cxx_std_20;")
      message(FATAL_ERROR "${_TARGET} must export cxx_std_20, got '${_COMPILE_FEATURES}'")
    endif()
  endif()
endforeach()
foreach(_TARGET IN LISTS _PUBLIC_TARGETS)
  if(TARGET ${_TARGET})
    foreach(_PROPERTY IN LISTS _PUBLIC_PROPERTIES)
      get_target_property(_VALUE ${_TARGET} ${_PROPERTY})
      if(_VALUE AND ("${_VALUE}" MATCHES "${_PRIVATE_BACKEND_LOWER}" OR
                     "${_VALUE}" MATCHES "${_PRIVATE_BACKEND_UPPER}" OR
                     "${_VALUE}" MATCHES "${_PRIVATE_BACKEND_CAMEL}"))
        message(FATAL_ERROR "${_TARGET} ${_PROPERTY} exposes a private mesh backend token: '${_VALUE}'")
      endif()
    endforeach()
  endif()
endforeach()

message(STATUS "Package identity smoke check '${CHECK_SHAPE}/${CHECK_ORDER}' passed")